### ISSUE TITLE
The `Download` feature dosen't work when using `auto wallpaper`

### ISSUE THREAD

**Issue by KAGEYAM4** [ammargitham/WallFlow#48]
There is a option when using `auto-wallpaper`, which says `Download wallpaper when used in auto wallpaper` , I have enabled the settings, and when i check my gallery there are no wallpapers.

Wallflow - v2.2.1
Android - 12 (Awaken OS)

**Comment by ammargitham** [comment]
Fixed in v2.3,0

**Comment by KAGEYAM4** [comment]
> Fixed in v2.3,0

It wasn't working, so i reset the app data and still not working. One thing i noticed that the app dosen't ask storage permission, i checked permission and it only has `Network` and `Sensors`. There app dosen't ask for `storage` permission, also it dosen't ask where to save those downloaded wallpapers. What is the default location for saved wallpapers?

**Comment by ammargitham** [comment]
Android 12 does not require the storage permissions to save to the download folder. Wallpapers should get saved to Download/Wallflow directory. Can you check that directory?
Are you able to download wallpapers manually?

**Comment by KAGEYAM4** [comment]
@ammargitham  So  Download/Wallflow directory didn't existed, and then i tried to download wallpaper manually as you said. It was successful and Download/Wallflow got created during the process. Now i tried auto wallpaper and now wallpaper was automatically being downloaded.

Above was android-12 

On android-11 (waydroid), auto-wallpaper was not donloading wallpaper, and there was no Download/Wallflow directory, so i went ahead and cerated Download/Wallflow manually. now auto-wallpaper is downloading wallpaper when `auto-wallpaper-download` in on.

so i think the bug is with the directory not being present.

**Comment by ammargitham** [comment]
Thanks with the investigation. Will try to fix this.

**Comment by ammargitham** [comment]
Can you test if this updated debug apk fixes this problem for you? You won't need to uninstall any existing release builds. Debug apk have their own package name.

[app-base-debug.zip](https://github.com/ammargitham/WallFlow/files/13785849/app-base-debug.zip)

**Comment by KAGEYAM4** [comment]
> Thanks with the investigation. Will try to fix this.

yes this one works.

**Comment by ammargitham** [comment]
Great! Thanks, the directory was the problem.

**Comment by ammargitham** [comment]
Released in v2.3.1
